name: CI (Flutter + SonarCloud)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze & Scan
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Installe Flutter sur le runner Windows
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'       # ou fixe une version: '3.24.3'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      # (Optionnel mais recommandé) Analyse statique + tests + couverture
      - name: Analyze
        run: flutter analyze

      - name: Test with coverage
        run: flutter test --coverage

      # Lancement du scan SonarCloud (PAS l’action SonarQube)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # token SonarCloud (User > Security)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # fourni automatiquement par GitHub
